image:
  file: .gitpod.dockerfile

tasks:
  - name: Frontend
    init: |
      cd client
      yarn
    command: yarn dev
  - name: Database
    init: |
      pg_start
      gp sync-done db
    command: psql -c "create database qrator;"
  - name: Server
    init: |
      gp sync-await db
      cd server
    command: go run server.go

ports:
  - port: 3000
    onOpen: open-browser
