image:
  file: .gitpod.dockerfile

tasks:
  - name: Frontend
    init: |
      cd client
      yarn
    command: yarn dev
  - name: Database
    init: |
      pg_start
      psql -c "create database qrator;"
      gp sync-done db
  - name: Server
    init: |
      gp sync-await db
      cd server
      go build
    command: ./server

ports:
  - port: 3000
    onOpen: open-browser
